name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up environment variables
        run: |
          touch .env
          echo "FLASK_SECRET=${{ secrets.FLASK_SECRET }}" > .env
          echo "RUNNING_ON=${{ vars.RUNNING_ON }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "CLIENT_ID=${{ vars.CLIENT_ID }}" >> .env
          echo "AUTH_URL=${{ vars.AUTH_URL }}" >> .env
          echo "TOKEN_URL=${{ vars.TOKEN_URL }}" >> .env
          echo "API_BASE_URL=${{ vars.API_BASE_URL }}" >> .env
          echo "REDIRECT_URI=${{ vars.REDIRECT_URI }}" >> .env
          cat .env
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
